/**
 * Bestiary metadata for monster rosters and descriptions.
 */

export type EnemyKind = string;

export const KIND_INFO: Record<EnemyKind, { label: string; icon: string; blurb: string }> = {
  zombie: { label: "Zombie", icon: "🧟", blurb: "shambles in a drag-limp, aggressive sprint, red claw slash attacks, and blood-splatter collapse" },
  spider: { label: "Spider", icon: "🕷️", blurb: "wolf spider swinging dual nunchucks in fast flurries" },
  brute: { label: "Brute", icon: "🦍", blurb: "thick hide, heavy swing, enrages when hurt" },
  spitter: { label: "Demon", icon: "👹", blurb: "floating split-face ghost demon with Jekyll-Hyde / Two-Face visage shooting magic lasers" },
  ghost: { label: "Ghost", icon: "👻", blurb: "drifts through walls; untouchable until it strikes" },
  bat: { label: "Bat", icon: "🦇", blurb: "wobbles in on a drunken line — hard to swat" },
  slime: { label: "Slime", icon: "🟢", blurb: "splits into two fast minis when killed" },
  sporeling: { label: "Spore", icon: "🍄", blurb: "toxic bioluminescent mushroom that spews poison mist" },
  jester: { label: "Jester", icon: "🤡", blurb: "fires the plate off its head — and the plate ricochets" },
  croaker: { label: "Croaker", icon: "🐸", blurb: "squat emerald frog with twin eye-beams that hops walls and flattens on death" },
  rotortail: { label: "Crawler Bot", icon: "🤖", blurb: "spider robot with a 360 spinning head and eye lasers" },
  stiltneck: { label: "Stiltneck", icon: "💣", blurb: "slings a lit bomb from nine tiles out — the blast catches its own horde too" },
  fish_feet: { label: "Fish Feet", icon: "👟", blurb: "a smoking fish walking on white Converse sneakers that delivers heavy kick strikes" },
  reaper: { label: "Death Dealer", icon: "☠️", blurb: "cannot be hurt. It only ever gets faster" },
  goblin: { label: "Goblin", icon: "👺", blurb: "kicks you off your line; shrugs off a standing poke" },
  pin: { label: "Bowling Pin", icon: "🎳", blurb: "does not fight. It scores — and it chains" },
  golem: { label: "Brick Golem", icon: "🗿", blurb: "rooted furniture with teeth; needs smash-speed" },
  chomper: { label: "Chomper", icon: "🪴", blurb: "giant Venus flytrap with snapping jaws that grabs and holds you until you spam free" },
  magnet: { label: "Magnet Crawler", icon: "🧲", blurb: "drags your momentum off its line" },
  webspinner: { label: "Webspinner", icon: "🕸️", blurb: "webs you at range and slows the ride" },
  hound: { label: "Hound", icon: "🐺", blurb: "locks a dash and charges the gap" },
  bloater: { label: "Bloater", icon: "🫧", blurb: "bursts into a burning puddle — don't melee it close" },
  necromancer: { label: "Necromancer", icon: "🧟‍♂️", blurb: "floating dark-robed zombie necromancer casting green summoning flames" },
  warden: { label: "Warden", icon: "🧟", blurb: "massive Frankenstein orc brute patched together from scrap metal and garbage" },
  crystalback: { label: "Crystal Phantom", icon: "💎", blurb: "ethereal crystal phantom ghost with orbiting prismatic shards" },
  mimic: { label: "Mimic Ghost", icon: "📦", blurb: "poltergeist treasure chest ghost that lashes with fangs and a spectral tongue" },
  platypus: { label: "Iron Platypus", icon: "🦫", blurb: "armored beast with duck bill and heavy segmented steel tail" },
  espresso: { label: "Espresso Cup", icon: "☕", blurb: "hyperactive caffeine terror that spins like a Disneyland teacup" },
  gnome: { label: "Lawnmower Gnome", icon: "🧙‍♂️", blurb: "pipe-smoking garden gnome that attacks with a roaring lawnmower" },
  cigarette: { label: "Walking Cigarette", icon: "🚬", blurb: "1950s cartoon cigarette with gloves and shoes" },
  toucan: { label: "Toucan", icon: "🦜", blurb: "tropical aerial striker with a massive rainbow beak" },
  jade_buddha: { label: "Jade Buddha", icon: "🪷", blurb: "serene emerald statue with devastating belly slam" },
  burger: { label: "Burger Beast", icon: "🍔", blurb: "floating hamburger with lobster eyestalks" },
  fries: { label: "Fry Sentinel", icon: "🍟", blurb: "sentient red fry carton with crinkle-cut limbs launching fry rockets" },
  milkshake: { label: "Toxic Shake", icon: "🥤", blurb: "erratic fast-food milkshake cup spraying corrosive shake" },
  crawling_hand: { label: "Crawling Hand", icon: "🖐️", blurb: "severed stitched hand that skitters on fingertips" },
  sumo_ninja: { label: "Drunk Sumo Ninja", icon: "🥷", blurb: "rotund sumo wrestler in ninja attire whipping sharp ninja stars" },
  zippo: { label: "Pyro Zippo", icon: "🔥", blurb: "1960s cartoon flip-top lighter with a dancing flame face" },
  cerberus: { label: "Cerberus", icon: "🐕", blurb: "three-headed hellhound that lunges with iron jaws" },
  clam: { label: "Old Clam", icon: "🦪", blurb: "weathered geriatric bivalve with dark sunglasses and walrus mustache" },
  crab: { label: "Sir Pinch-a-Lot", icon: "🦀", blurb: "Victorian gentleman crab wearing top hat and monocle" },
  medusa: { label: "Gorgon Medusa", icon: "🐍", blurb: "serpentine Gorgon Queen with living snake hair and petrifying gaze" },
  dracula: { label: "Count Dracula", icon: "🧛", blurb: "classic Castlevania vampire lord with high-collared bat cape" },
  spinning_top: { label: "Spinning Top", icon: "🌪️", blurb: "vintage wooden spinning top monster with brass rim and spiral eyes" },
  pinball_boss: { label: "Pinball Boss", icon: "⚪", blurb: "colossal gleaming chrome pinball boss with segmented iron plating" },
  shark_trapper: { label: "Shark Trapper", icon: "🦈", blurb: "bipedal hammerhead shark gangster in pinstripe fedora" },
  octopus_gunner: { label: "Octopus Gunner", icon: "🐙", blurb: "eight-armed octopus Don in charcoal trench coat" },
  clownfish_mob: { label: "Clownfish Mob", icon: "🐠", blurb: "sneering orange clownfish enforcer with gold tooth" },
  lionfish_mob: { label: "Lionfish Mob", icon: "🦁", blurb: "regal lionfish underboss in deep purple zoot suit" },
  pufferfish_mob: { label: "Pufferfish Capo", icon: "🐡", blurb: "rotund pufferfish capo in tight double-breasted suit" },
  swordfish_mob: { label: "Swordfish Hitman", icon: "🗡️", blurb: "sleek silver swordfish hitman in tailored black vest" },
  moray_mob: { label: "Moray Enforcer", icon: "🐍", blurb: "hulking green moray eel bruiser in torn pinstripe shirt" },
  seahorse_mob: { label: "Seahorse Consigliere", icon: "♟️", blurb: "slender golden seahorse consigliere in ornate silk waistcoat" },
  gas_can: { label: "Gas Canister", icon: "⛽", blurb: "flammable red jerrycan monster with exhaust pipe spout" },
  hamster_ball: { label: "Hamster Ball", icon: "🐹", blurb: "speed demon rodent inside reinforced plexiglass sphere" },
  giant_ascii_human: { label: "ASCII Titan", icon: "💾", blurb: "towering monochromatic green phosphor wireframe colossus" },
  pit_peeper: { label: "Pit Peeper", icon: "👀", blurb: "hairy orange sewer critter with bloodshot eyes on stalks poking out of armpits" },
  dumpster_dan: { label: "Dumpster Dan", icon: "🗑️", blurb: "wrinkled green municipal trash bag body with backwards baseball cap" },
  toaster_gremlin: { label: "Toaster Gremlin", icon: "🍞", blurb: "gangly purple goblin with a shiny 1950s chrome countertop toaster head" },
  lip_flapper: { label: "Lip Flapper", icon: "👄", blurb: "black-and-red candy-striped accordion stalk topped with colossal wax lips" },
  blaster_frank: { label: "Blaster Frank", icon: "🔫", blurb: "short squat gangster in rumpled pinstripe suit dual-wielding snub-nose revolvers" },
  tavern_alchemist: { label: "Tavern Alchemist", icon: "🧪", blurb: "eccentric potion brewer with bubble flasks and glowing reagents" },
  tavern_armorer: { label: "Tavern Armorer", icon: "🛡️", blurb: "stout dwarven metalsmith forging enchanted iron plates" },
  tavern_dealer: { label: "Tavern Dealer", icon: "🃏", blurb: "shadowy card shark with feathered fedora dealing mystical tarot" },
  tavern_gambler: { label: "Tavern Gambler", icon: "🎲", blurb: "dashing rogue rolling high-stakes bone dice" },
  tavern_smith: { label: "Tavern Blacksmith", icon: "🔨", blurb: "burly forge master hammering glowing Damascus blades" },
};

export const KIND_IDS = Object.keys(KIND_INFO) as EnemyKind[];
